(() => {
  "use strict";
  const STORAGE_KEY = "bacochu-language";
  const supported = ["ko", "en", "ja", "zh-CN"];
  const ko = {
    "언어 선택":"언어 선택","바코추":"바코추","부산 바다 코스 추천":"부산 바다 코스 추천","오늘의 기분에 꼭 맞는\n부산 바다 여행을 시작해 보세요.":"오늘의 기분에 꼭 맞는\n부산 바다 여행을 시작해 보세요.","어디로 떠나볼까요?":"어디로 떠나볼까요?","바다를 즐기는 방법":"바다를 즐기는 방법","맑은 날씨":"맑은 날씨","맞춤 코스 찾기":"맞춤 코스 찾기","내 취향에 꼭 맞는 여행 코스":"내 취향에 꼭 맞는 여행 코스","여행 코스 공유":"여행 코스 공유","나만의 부산 바다 여행을 나눠요":"나만의 부산 바다 여행을 나눠요","월별 이벤트":"월별 이벤트","이달의 축제와 즐길 거리":"이달의 축제와 즐길 거리",
    "어떤 여행을 원하세요?":"어떤 여행을 원하세요?","각 항목에서 하나씩 골라주세요.":"각 항목에서 하나씩 골라주세요.","여행 분위기":"여행 분위기","조용한 휴식":"조용한 휴식","활기찬 관광":"활기찬 관광","사진 촬영":"사진 촬영","함께 가는 사람":"함께 가는 사람","혼자":"혼자","친구":"친구","가족":"가족","원하는 활동":"원하는 활동","산책":"산책","맛집":"맛집","바다 체험":"바다 체험","코스 추천받기":"코스 추천받기","나만의 바다 코스":"나만의 바다 코스","처음부터 다시 선택하기":"처음부터 다시 선택하기",
    "부산 바다에서 보낸 특별한 하루를 함께 나눠보세요.":"부산 바다에서 보낸 특별한 하루를 함께 나눠보세요.","여행 코스 둘러보기":"여행 코스 둘러보기","여행자들이 공유한 코스를 만나요":"여행자들이 공유한 코스를 만나요","새 코스 올리기":"새 코스 올리기","나만의 코스를 직접 작성해요":"나만의 코스를 직접 작성해요","마음에 드는 코스를 눌러 자세히 보세요.":"마음에 드는 코스를 눌러 자세히 보세요.","+ 새 코스":"+ 새 코스","전체 코스":"전체 코스","즐겨찾기":"즐겨찾기",
    "모든 항목은 필수입니다.":"모든 항목은 필수입니다.","코스 제목":"코스 제목","작성자 이름 또는 별명":"작성자 이름 또는 별명","부산의 바다 또는 해수욕장 선택":"부산의 바다 또는 해수욕장 선택","선택해 주세요":"선택해 주세요","방문 장소":"방문 장소","코스 장소 개수":"코스 장소 개수","최소 1개, 최대 6개까지 순서대로 등록할 수 있어요.":"최소 1개, 최대 6개까지 순서대로 등록할 수 있어요.","예상 소요 시간":"예상 소요 시간","누구와 가기 좋은지":"누구와 가기 좋은지","코스 분위기":"코스 분위기","휴식":"휴식","관광":"관광","체험":"체험","코스 소개와 추천 이유":"코스 소개와 추천 이유","코스 등록하기":"코스 등록하기",
    "공유 여행 코스":"공유 여행 코스","월별 바다 행사":"월별 바다 행사","부산 바다와 해수욕장 주변의 다채로운 행사를 월별로 둘러보세요. 아래 내용은 기능 확인을 위한 예시입니다.":"부산 바다와 해수욕장 주변의 다채로운 행사를 월별로 둘러보세요. 아래 내용은 기능 확인을 위한 예시입니다.","행사 월 선택":"행사 월 선택","전체":"전체","축제":"축제","공연":"공연","전시":"전시",
    "첫 화면으로 돌아가기":"첫 화면으로 돌아가기","취향 선택으로 돌아가기":"취향 선택으로 돌아가기","홈으로 가기":"홈으로 가기","뒤로 가기":"뒤로 가기","목록으로 돌아가기":"목록으로 돌아가기","행사 목록으로 돌아가기":"행사 목록으로 돌아가기","여행 코스 보기 필터":"여행 코스 보기 필터","행사 종류 필터":"행사 종류 필터","장소 개수 줄이기":"장소 개수 줄이기","장소 개수 늘리기":"장소 개수 늘리기","코스 장소 개수 선택":"코스 장소 개수 선택",
    "예: 광안리 노을 산책 코스":"예: 광안리 노을 산책 코스","예: 바다사랑":"예: 바다사랑","예: 약 4시간":"예: 약 4시간","코스의 매력과 추천 이유를 알려주세요.":"코스의 매력과 추천 이유를 알려주세요."
  };
  const en = {
    "바코추 | 부산 바다 코스 추천":"Bacochu | Busan seaside courses","취향에 맞는 부산 바다 코스를 추천하는 바코추입니다.":"Bacochu recommends Busan seaside courses tailored to your taste.","언어 선택":"Language","바코추":"Bacochu","부산 바다 코스 추천":"Busan seaside course recommendations","오늘의 기분에 꼭 맞는\n부산 바다 여행을 시작해 보세요.":"Start a Busan seaside trip\nthat matches your mood today.","어디로 떠나볼까요?":"Where shall we go?","바다를 즐기는 방법":"Ways to enjoy the sea","맑은 날씨":"Sunny weather","맞춤 코스 찾기":"Find my course","내 취향에 꼭 맞는 여행 코스":"A trip tailored to your taste","여행 코스 공유":"Share a travel course","나만의 부산 바다 여행을 나눠요":"Share your own Busan sea trip","월별 이벤트":"Monthly events","이달의 축제와 즐길 거리":"Festivals and activities this month","어떤 여행을 원하세요?":"What kind of trip would you like?","각 항목에서 하나씩 골라주세요.":"Choose one option in each section.","여행 분위기":"Travel mood","조용한 휴식":"Quiet relaxation","활기찬 관광":"Lively sightseeing","사진 촬영":"Photography","함께 가는 사람":"Travel companion","혼자":"Solo","친구":"Friends","가족":"Family","원하는 활동":"Preferred activity","산책":"Walking","맛집":"Food","바다 체험":"Sea activities","코스 추천받기":"Get recommendation","나만의 바다 코스":"My seaside course","처음부터 다시 선택하기":"Start over","부산 바다에서 보낸 특별한 하루를 함께 나눠보세요.":"Share your special day by the Busan sea.","여행 코스 둘러보기":"Browse travel courses","여행자들이 공유한 코스를 만나요":"Discover courses shared by travelers","새 코스 올리기":"Post a new course","나만의 코스를 직접 작성해요":"Create your own course","마음에 드는 코스를 눌러 자세히 보세요.":"Select a course to see details.","+ 새 코스":"+ New course","전체 코스":"All courses","즐겨찾기":"Favorites","모든 항목은 필수입니다.":"All fields are required.","코스 제목":"Course title","작성자 이름 또는 별명":"Author name or nickname","부산의 바다 또는 해수욕장 선택":"Choose a Busan sea or beach","선택해 주세요":"Please select","방문 장소":"Places to visit","코스 장소 개수":"Number of places","최소 1개, 최대 6개까지 순서대로 등록할 수 있어요.":"Add 1 to 6 places in order.","예상 소요 시간":"Estimated duration","누구와 가기 좋은지":"Best companion","코스 분위기":"Course mood","휴식":"Relaxation","관광":"Sightseeing","체험":"Activity","코스 소개와 추천 이유":"Course description and recommendation","코스 등록하기":"Post course","공유 여행 코스":"Shared travel course","월별 바다 행사":"Monthly seaside events","부산 바다와 해수욕장 주변의 다채로운 행사를 월별로 둘러보세요. 아래 내용은 기능 확인을 위한 예시입니다.":"Browse monthly events near Busan's sea and beaches. These are samples for demonstrating the feature.","행사 월 선택":"Select month","전체":"All","축제":"Festival","공연":"Performance","전시":"Exhibition","첫 화면으로 돌아가기":"Return to first screen","취향 선택으로 돌아가기":"Return to preferences","홈으로 가기":"Go home","뒤로 가기":"Go back","목록으로 돌아가기":"Return to list","행사 목록으로 돌아가기":"Return to event list","여행 코스 보기 필터":"Course filters","행사 종류 필터":"Event type filters","장소 개수 줄이기":"Decrease places","장소 개수 늘리기":"Increase places","코스 장소 개수 선택":"Select number of places","예: 광안리 노을 산책 코스":"e.g. Gwangalli sunset walk","예: 바다사랑":"e.g. Sea Lover","예: 약 4시간":"e.g. About 4 hours","코스의 매력과 추천 이유를 알려주세요.":"Describe the course and why you recommend it."
  };
  const ja = Object.assign({}, en, {"언어 선택":"言語","바코추":"バコチュ","부산 바다 코스 추천":"釜山の海コースおすすめ","오늘의 기분에 꼭 맞는\n부산 바다 여행을 시작해 보세요.":"今日の気分にぴったりの\n釜山の海旅を始めましょう。","어디로 떠나볼까요?":"どこへ出かけますか？","바다를 즐기는 방법":"海の楽しみ方","맞춤 코스 찾기":"おすすめコースを探す","내 취향에 꼭 맞는 여행 코스":"好みにぴったりの旅行コース","여행 코스 공유":"旅行コースを共有","월별 이벤트":"月別イベント","어떤 여행을 원하세요?":"どんな旅をご希望ですか？","각 항목에서 하나씩 골라주세요.":"各項目から一つずつ選んでください。","여행 분위기":"旅の雰囲気","조용한 휴식":"静かな休息","활기찬 관광":"にぎやかな観光","사진 촬영":"写真撮影","함께 가는 사람":"同行者","혼자":"一人","친구":"友達","가족":"家族","원하는 활동":"希望するアクティビティ","산책":"散歩","맛집":"グルメ","바다 체험":"海の体験","코스 추천받기":"コースを提案","처음부터 다시 선택하기":"最初から選び直す","여행 코스 둘러보기":"旅行コースを見る","새 코스 올리기":"新しいコースを投稿","전체 코스":"すべてのコース","즐겨찾기":"お気に入り","모든 항목은 필수입니다.":"すべて必須項目です。","코스 제목":"コース名","작성자 이름 또는 별명":"投稿者名またはニックネーム","선택해 주세요":"選択してください","방문 장소":"訪問場所","코스 장소 개수":"場所の数","예상 소요 시간":"所要時間","코스 분위기":"コースの雰囲気","코스 등록하기":"コースを登録","월별 바다 행사":"月別海イベント","행사 월 선택":"開催月を選択","전체":"すべて","축제":"祭り","공연":"公演","전시":"展示","체험":"体験","홈으로 가기":"ホームへ","뒤로 가기":"戻る","목록으로 돌아가기":"一覧へ戻る"});
  const zh = Object.assign({}, en, {"언어 선택":"语言","바코추":"Bacochu","부산 바다 코스 추천":"釜山海滨路线推荐","오늘의 기분에 꼭 맞는\n부산 바다 여행을 시작해 보세요.":"开启一段符合今日心情的\n釜山海滨之旅吧。","어디로 떠나볼까요?":"想去哪里？","바다를 즐기는 방법":"享受大海的方式","맞춤 코스 찾기":"寻找定制路线","내 취향에 꼭 맞는 여행 코스":"符合你喜好的旅行路线","여행 코스 공유":"分享旅行路线","월별 이벤트":"每月活动","어떤 여행을 원하세요?":"你想要怎样的旅行？","각 항목에서 하나씩 골라주세요.":"请在每项中选择一个选项。","여행 분위기":"旅行氛围","조용한 휴식":"安静休闲","활기찬 관광":"活力观光","사진 촬영":"摄影","함께 가는 사람":"同行者","혼자":"独自","친구":"朋友","가족":"家人","원하는 활동":"想要的活动","산책":"散步","맛집":"美食","바다 체험":"海上体验","코스 추천받기":"获取路线推荐","처음부터 다시 선택하기":"重新选择","여행 코스 둘러보기":"浏览旅行路线","새 코스 올리기":"发布新路线","전체 코스":"全部路线","즐겨찾기":"收藏","모든 항목은 필수입니다.":"所有项目均为必填。","코스 제목":"路线标题","작성자 이름 또는 별명":"作者姓名或昵称","선택해 주세요":"请选择","방문 장소":"游览地点","코스 장소 개수":"地点数量","예상 소요 시간":"预计用时","코스 분위기":"路线氛围","코스 등록하기":"发布路线","월별 바다 행사":"每月海滨活动","행사 월 선택":"选择活动月份","전체":"全部","축제":"庆典","공연":"演出","전시":"展览","체험":"体验","홈으로 가기":"返回首页","뒤로 가기":"返回","목록으로 돌아가기":"返回列表"});
  Object.assign(en, {
    "좋아요":"Like","좋아요 취소":"Unlike","즐겨찾기 저장":"Save favorite","즐겨찾기 해제":"Remove favorite","저장됨":"Saved","삭제":"Delete","댓글":"Comments","별명":"Nickname","댓글 내용":"Comment","댓글 등록":"Post comment","코스 삭제":"Delete course","날짜":"Date","장소":"Place","바다":"Sea","추천 대상":"Recommended for","이용 팁":"Tips","찾아가는 방법":"Directions","아직 즐겨찾기한 코스가 없습니다.":"No favorite courses yet.","마음에 드는 코스의 북마크 버튼을 눌러 저장해보세요!":"Use the bookmark button to save a course you like!","표시할 장소 정보가 없습니다.":"No place information available.","댓글은 현재 이 브라우저에만 저장되며 다른 이용자와 공유되지 않습니다.":"Comments are stored only in this browser and are not shared.","아직 작성된 댓글이 없습니다. 첫 댓글을 남겨보세요!":"No comments yet. Leave the first one!","작성 시각 정보 없음":"Time unavailable","댓글이 등록되었습니다.":"Comment posted.","댓글이 삭제되었습니다.":"Comment deleted.","이 댓글을 삭제하시겠습니까?":"Delete this comment?","정말 이 코스를 삭제하시겠습니까?":"Are you sure you want to delete this course?","코스가 삭제되었습니다":"Course deleted.","익명 로그인 중입니다. 잠시 후 다시 등록해 주세요.":"Waiting for anonymous sign-in. Please try again shortly.","코스를 등록하지 못했습니다. 네트워크 연결을 확인해 주세요.":"Could not post the course. Check your network connection.","이달에는 등록된 행사가 없습니다":"There are no events this month.","총 {count}개의 장소":"{count} places total","{number}번째 장소":"Place {number}","장소명":"Place name","장소 설명":"Place description","주소":"Address","여행 취향 세 항목을 모두 선택해 주세요.":"Please select all three travel preferences.","예상 소요 시간 {time}":"Estimated duration {time}","이 코스를 추천하는 이유":"Why we recommend this course","방문 장소 {count}곳":"{count} places to visit","댓글 {count}개":"{count} comments","작성한 장소 정보가 삭제됩니다. 줄이시겠습니까?":"Entered place details will be removed. Continue?","관리 비밀번호를 입력해 주세요.":"Enter the management password.","본인이 작성한 게시물만 삭제할 수 있습니다.":"You can delete only your own post.","네트워크 오류가 발생했습니다.":"A network error occurred.","로딩 중":"Loading","저장 중":"Saving","데이터 없음":"No data","인증 대기 중":"Waiting for authentication"
  });
  Object.assign(ja, {"바코추 | 부산 바다 코스 추천":"バコチュ | 釜山の海コース","취향에 맞는 부산 바다 코스를 추천하는 바코추입니다.":"好みに合う釜山の海コースをおすすめするバコチュです。",
    "좋아요":"いいね","좋아요 취소":"いいねを解除","즐겨찾기 저장":"お気に入りに保存","즐겨찾기 해제":"お気に入りを解除","저장됨":"保存済み","삭제":"削除","댓글":"コメント","별명":"ニックネーム","댓글 내용":"コメント内容","댓글 등록":"コメントを投稿","코스 삭제":"コースを削除","날짜":"日付","장소":"場所","바다":"海","추천 대상":"おすすめ対象","이용 팁":"利用のヒント","찾아가는 방법":"アクセス","아직 즐겨찾기한 코스가 없습니다.":"お気に入りのコースはまだありません。","표시할 장소 정보가 없습니다.":"表示する場所情報がありません。","아직 작성된 댓글이 없습니다. 첫 댓글을 남겨보세요!":"コメントはまだありません。最初のコメントをどうぞ！","댓글이 등록되었습니다.":"コメントを登録しました。","댓글이 삭제되었습니다.":"コメントを削除しました。","이 댓글을 삭제하시겠습니까?":"このコメントを削除しますか？","정말 이 코스를 삭제하시겠습니까?":"本当にこのコースを削除しますか？","코스가 삭제되었습니다":"コースを削除しました。","이달에는 등록된 행사가 없습니다":"今月のイベントはありません。","총 {count}개의 장소":"全{count}か所","장소명":"場所名","장소 설명":"場所の説明","주소":"住所","여행 취향 세 항목을 모두 선택해 주세요.":"旅行の好みを3項目すべて選んでください。","로딩 중":"読み込み中","저장 중":"保存中","데이터 없음":"データなし","인증 대기 중":"認証待ち","네트워크 오류가 발생했습니다.":"ネットワークエラーが発生しました。"
  });
  Object.assign(zh, {"바코추 | 부산 바다 코스 추천":"Bacochu | 釜山海滨路线","취향에 맞는 부산 바다 코스를 추천하는 바코추입니다.":"Bacochu 为您推荐符合喜好的釜山海滨路线。",
    "좋아요":"点赞","좋아요 취소":"取消点赞","즐겨찾기 저장":"添加收藏","즐겨찾기 해제":"取消收藏","저장됨":"已收藏","삭제":"删除","댓글":"评论","별명":"昵称","댓글 내용":"评论内容","댓글 등록":"发表评论","코스 삭제":"删除路线","날짜":"日期","장소":"地点","바다":"海滨","추천 대상":"推荐人群","이용 팁":"使用提示","찾아가는 방법":"交通方式","아직 즐겨찾기한 코스가 없습니다.":"暂无收藏路线。","표시할 장소 정보가 없습니다.":"没有可显示的地点信息。","아직 작성된 댓글이 없습니다. 첫 댓글을 남겨보세요!":"暂无评论，来发表第一条吧！","댓글이 등록되었습니다.":"评论已发布。","댓글이 삭제되었습니다.":"评论已删除。","이 댓글을 삭제하시겠습니까?":"要删除这条评论吗？","정말 이 코스를 삭제하시겠습니까?":"确定要删除这条路线吗？","코스가 삭제되었습니다":"路线已删除。","이달에는 등록된 행사가 없습니다":"本月暂无活动。","총 {count}개의 장소":"共 {count} 个地点","장소명":"地点名称","장소 설명":"地点说明","주소":"地址","여행 취향 세 항목을 모두 선택해 주세요.":"请选择全部三项旅行偏好。","로딩 중":"加载中","저장 중":"保存中","데이터 없음":"暂无数据","인증 대기 중":"等待认证","네트워크 오류가 발생했습니다.":"发生网络错误。"
  });
  const translations = { ko, en, ja, "zh-CN": zh };
  let language;
  try { language = localStorage.getItem(STORAGE_KEY); } catch (_) { language = null; }
  if (!supported.includes(language)) {
    const browser = navigator.language || "ko";
    language = browser.toLowerCase().startsWith("zh") ? "zh-CN" : supported.find((code) => browser.toLowerCase().startsWith(code.toLowerCase())) || "ko";
  }
  const originalNodes = new Map();
  const interpolate = (value, vars) => Object.entries(vars).reduce((text, [key, replacement]) => text.replaceAll(`{${key}}`, replacement), value);
  function t(key, vars = {}) { return interpolate(translations[language]?.[key] ?? ko[key] ?? key, vars); }
  function apply(root = document) {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, { acceptNode: (node) => node.parentElement?.closest("script,style") ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT });
    const nodes = []; while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach((node) => {
      if (!originalNodes.has(node)) originalNodes.set(node, node.nodeValue);
      const original = originalNodes.get(node); const key = original.trim();
      if (ko[key]) node.nodeValue = original.replace(key, t(key));
    });
    root.querySelectorAll?.("[data-i18n]").forEach((el) => { el.textContent = t(el.dataset.i18n); });
    ["aria-label", "placeholder", "title"].forEach((attr) => root.querySelectorAll?.(`[${attr}]`).forEach((el) => { const marker = `i18nOriginal${attr.replace("-", "")}`; const key = el.dataset[marker] || el.getAttribute(attr); el.dataset[marker] = key; if (ko[key]) el.setAttribute(attr, t(key)); }));
    document.documentElement.lang = language;
    document.title = t("바코추 | 부산 바다 코스 추천");
    const description = document.querySelector('meta[name="description"]');
    if (description) description.content = t("취향에 맞는 부산 바다 코스를 추천하는 바코추입니다.");
    document.querySelectorAll("#event-month option").forEach((option) => {
      option.textContent = new Intl.DateTimeFormat(({ ko: "ko-KR", en: "en-US", ja: "ja-JP", "zh-CN": "zh-CN" })[language], { month: "long", timeZone: "UTC" }).format(new Date(Date.UTC(2026, Number(option.value) - 1, 1)));
    });
    const select = document.querySelector("#language-select"); if (select) select.value = language;
  }
  function setLanguage(next) { if (!supported.includes(next)) return; language = next; try { localStorage.setItem(STORAGE_KEY, next); } catch (_) {} apply(); window.dispatchEvent(new CustomEvent("bacochu:languagechange", { detail: { language } })); }
  window.i18n = { t, apply, setLanguage, get language() { return language; }, translations, supported };
  document.addEventListener("DOMContentLoaded", () => { apply(); document.querySelector("#language-select")?.addEventListener("change", (event) => setLanguage(event.target.value)); });
})();
