(function (root) {
  "use strict";
  const L = (ko, en, ja, zh) => ({ ko, en, ja, "zh-CN": zh });
  const P = (ko, en, ja, zh) => L(ko, en, ja, zh);
  const course = (id, beach, name, places, duration, timeLabel, tags, reason, description = reason) => ({ id, beach, name, places, duration, timeLabel, tags, reason, description, builtIn: true });
  const courses = [
    course("rec-gwangalli-night", "gwangalli", L("광안리 야경 감성 코스","Gwangalli Nightscape Course","広安里夜景エモーショナルコース","广安里夜景氛围路线"), [P("광안리해수욕장","Gwangalli Beach","広安里海水浴場","广安里海水浴场"),P("민락해변공원","Millak Beach Park","民楽海辺公園","民乐海滨公园"),P("광안대교 야경 조망","Gwangan Bridge night view","広安大橋の夜景","广安大桥夜景")], L("약 3시간","About 3 hours","約3時間","约3小时"), L("저녁","Evening","夜","晚上"), ["emotional","photo","friends","couple","evening","normal","night","lively"], L("감성적인 해변 산책과 광안대교 야경이 사진을 남기고 싶은 친구나 연인에게 잘 맞아요.","A scenic beach walk and Gwangan Bridge lights suit friends or couples who love atmospheric photos.","海辺の散歩と広安大橋の夜景は、写真を楽しみたい友人やカップルにぴったりです。","海滨散步与广安大桥夜景，很适合喜爱氛围感照片的朋友或情侣。")),
    course("rec-gwangalli-relax", "gwangalli", L("광안리 여유로운 반나절 코스","Relaxed Gwangalli Half-day","広安里のんびり半日コース","广安里悠闲半日路线"), [P("광안리해수욕장","Gwangalli Beach","広安里海水浴場","广安里海水浴场"),P("광안리 해변 카페 거리","Gwangalli beachfront cafés","広安里海辺のカフェ通り","广安里海滨咖啡街"),P("광안리 해변 산책로","Gwangalli beach promenade","広安里海辺の散歩道","广安里海滨步道")], L("약 3시간 30분","About 3.5 hours","約3時間30分","约3.5小时"), L("오후","Afternoon","午後","下午"), ["quiet","solo","cafe","walk","afternoon","easy","day-sea"], L("카페와 평탄한 해변 산책을 짧게 이어 가며 혼자서도 여유롭게 쉬기 좋아요.","Cafés and an easy, level promenade make a restful short solo trip.","カフェと平坦な海辺の散歩を気軽に楽しめ、一人旅にもおすすめです。","咖啡馆与平坦海滨步道衔接轻松，适合独自悠闲休息。")),
    course("rec-haeundae-classic", "haeundae", L("해운대 대표 관광 코스","Haeundae Highlights","海雲台定番観光コース","海云台经典观光路线"), [P("해운대해수욕장","Haeundae Beach","海雲台海水浴場","海云台海水浴场"),P("동백섬","Dongbaekseom Island","冬柏島","冬柏岛"),P("더베이101 주변","The Bay 101 area","ザ・ベイ101周辺","The Bay 101周边")], L("약 5시간","About 5 hours","約5時間","约5小时"), L("낮부터 저녁","Day to evening","昼から夜","白天至晚上"), ["lively","photo","family","afternoon","evening","many","famous","day-sea","night"], L("부산의 대표 해변과 동백섬, 마린시티 풍경을 차례로 만나 첫 부산 여행에 좋아요.","Busan's signature beach, Dongbaekseom and Marine City views make an ideal first visit.","代表的な海辺、冬柏島、マリンシティの景色を巡る初めての釜山旅行向けコースです。","依次游览代表海滩、冬柏岛与海洋城市景观，适合初次到访釜山。")),
    course("rec-haeundae-walk", "haeundae", L("해운대 바다 산책 코스","Haeundae Seaside Walk","海雲台海辺散歩コース","海云台海滨散步路线"), [P("해운대해수욕장","Haeundae Beach","海雲台海水浴場","海云台海水浴场"),P("동백섬 산책로","Dongbaekseom trail","冬柏島散策路","冬柏岛步道"),P("누리마루 APEC하우스 주변","Nurimaru APEC House area","ヌリマルAPECハウス周辺","世峰楼APEC会议之家周边")], L("약 3시간","About 3 hours","約3時間","约3小时"), L("오전 또는 오후","Morning or afternoon","午前または午後","上午或下午"), ["quiet","walk","nature","solo","family","morning","afternoon","normal","day-sea","famous"], L("해변에서 동백섬 숲길로 자연스럽게 이어져 바다와 자연을 천천히 감상하기 좋아요.","The beach flows naturally into Dongbaekseom's wooded trail for an unhurried nature walk.","海辺から冬柏島の林道へ自然につながり、海と自然をゆっくり楽しめます。","从海滩自然衔接冬柏岛林间步道，可悠闲欣赏海景与自然。")),
    course("rec-songjeong-active", "songjeong", L("송정 활동적인 바다 코스","Active Songjeong Seaside","松亭アクティブ海コース","松亭活力海滨路线"), [P("송정해수욕장","Songjeong Beach","松亭海水浴場","松亭海水浴场"),P("송정 해변 산책로","Songjeong beach promenade","松亭海辺の散歩道","松亭海滨步道"),P("죽도공원","Jukdo Park","竹島公園","竹岛公园")], L("약 4시간","About 4 hours","約4時間","约4小时"), L("낮","Daytime","昼","白天"), ["lively","sea","walk","friends","afternoon","normal","day-sea"], L("서핑 분위기의 송정 바다와 가까운 죽도공원을 함께 즐겨 활동적인 친구 여행에 좋아요.","Songjeong's surf atmosphere and nearby Jukdo Park suit an active trip with friends.","サーフィンの雰囲気と近くの竹島公園を楽しむ、友人とのアクティブな旅におすすめです。","体验松亭冲浪氛围并游览邻近竹岛公园，适合朋友活力出游。")),
    course("rec-songjeong-sunrise", "songjeong", L("송정 일출 감상 코스","Songjeong Sunrise Course","松亭日の出鑑賞コース","松亭日出观赏路线"), [P("송정해수욕장","Songjeong Beach","松亭海水浴場","松亭海水浴场"),P("죽도공원","Jukdo Park","竹島公園","竹岛公园"),P("송정 해변 쉼터","Songjeong beachfront rest area","松亭海辺の休憩所","松亭海滨休息区")], L("약 2시간 30분","About 2.5 hours","約2時間30分","约2.5小时"), L("이른 아침","Early morning","早朝","清晨"), ["quiet","photo","solo","morning","easy","sunrise","uncrowded","nature"], L("이른 아침 일출과 가까운 공원 산책을 조용히 즐기고 싶은 혼자 여행자에게 잘 맞아요.","An early sunrise and nearby park walk suit solo travelers seeking quiet scenery.","早朝の日の出と公園散歩を静かに楽しみたい一人旅にぴったりです。","清晨日出与邻近公园散步，适合喜爱安静风景的独行者。")),
    course("rec-songdo-view", "songdo", L("송도 바다 전망 코스","Songdo Ocean View Course","松島海景コース","松岛海景路线"), [P("송도해수욕장","Songdo Beach","松島海水浴場","松岛海水浴场"),P("송도구름산책로","Songdo Cloud Trails","松島スカイウォーク","松岛云端步道"),P("암남공원","Amnam Park","岩南公園","岩南公园")], L("약 4시간","About 4 hours","約4時間","约4小时"), L("낮","Daytime","昼","白天"), ["walk","family","photo","afternoon","normal","day-sea","famous","nature"], L("해변 전망 산책 뒤 가까운 암남공원의 숲과 해안을 만나 가족의 첫 방문에 좋아요.","A waterfront walk followed by Amnam Park's forest and coast is great for a family's first visit.","海辺の眺望散歩から岩南公園の森と海岸へ続き、家族の初訪問におすすめです。","海滨观景步道后前往岩南公园森林与海岸，适合家庭初访。")),
    course("rec-songdo-experience", "songdo", L("송도 체험·관광 코스","Songdo Experience & Sightseeing","松島体験・観光コース","松岛体验观光路线"), [P("송도해수욕장","Songdo Beach","松島海水浴場","松岛海水浴场"),P("송도해상케이블카","Busan Air Cruise","松島海上ケーブルカー","松岛海上缆车"),P("암남공원","Amnam Park","岩南公園","岩南公园")], L("약 5시간","About 5 hours","約5時間","约5小时"), L("오전 또는 오후","Morning or afternoon","午前または午後","上午或下午"), ["lively","sea","family","friends","morning","afternoon","many","day-sea","famous"], L("해수욕장과 해상케이블카, 도착지 쪽 암남공원이 한 동선으로 이어져 체험 여행에 좋아요.","The beach, cable car and Amnam Park connect in one practical route for an experiential trip.","海水浴場、海上ケーブルカー、到着側の岩南公園が一つの動線でつながります。","海水浴场、海上缆车和终点一侧的岩南公园连成顺畅体验路线。")),
    course("rec-dadaepo-sunset", "dadaepo", L("다대포 노을 감상 코스","Dadaepo Sunset Course","多大浦夕景鑑賞コース","多大浦晚霞观赏路线"), [P("다대포해수욕장","Dadaepo Beach","多大浦海水浴場","多大浦海水浴场"),P("고우니생태길","Gouni Ecological Trail","コウニ生態道","Gouni生态步道"),P("다대포 노을 전망 구간","Dadaepo sunset viewpoint","多大浦夕景展望区間","多大浦晚霞观景区")], L("약 3시간","About 3 hours","約3時間","约3小时"), L("늦은 오후부터 저녁","Late afternoon to evening","午後遅くから夜","傍晚至晚上"), ["quiet","photo","nature","solo","afternoon","evening","easy","sunset","uncrowded"], L("생태길과 넓은 백사장이 노을 방향으로 이어져 조용히 사진과 자연을 즐기기 좋아요.","The ecological trail and broad beach lead into sunset views for peaceful nature photography.","生態道と広い砂浜から夕景へ続き、静かに自然と写真を楽しめます。","生态步道与宽阔沙滩衔接晚霞，适合安静欣赏自然与摄影。")),
    course("rec-dadaepo-eco", "dadaepo", L("다대포 생태 산책 코스","Dadaepo Eco Walk","多大浦生態散歩コース","多大浦生态散步路线"), [P("다대포해수욕장","Dadaepo Beach","多大浦海水浴場","多大浦海水浴场"),P("고우니생태길","Gouni Ecological Trail","コウニ生態道","Gouni生态步道"),P("몰운대","Molundae","没雲台","没云台")], L("약 4시간 30분","About 4.5 hours","約4時間30分","约4.5小时"), L("낮","Daytime","昼","白天"), ["quiet","walk","nature","solo","family","afternoon","many","day-sea","uncrowded"], L("습지 생태길에서 몰운대 숲길까지 다양한 자연을 걷고 싶은 여행자에게 좋아요.","Wetland and woodland trails offer varied nature for solo travelers or families who enjoy walking.","湿地の生態道から没雲台の林道まで、多様な自然を歩きたい方におすすめです。","从湿地生态步道走到没云台林间道，适合喜爱多样自然的游客。")),
    course("rec-ilgwang-quiet", "ilgwang", L("일광 한적한 바다 코스","Quiet Ilgwang Seaside","日光静かな海コース","日光宁静海滨路线"), [P("일광해수욕장","Ilgwang Beach","日光海水浴場","日光海水浴场"),P("일광해수욕장 산책로","Ilgwang Beach promenade","日光海水浴場散歩道","日光海水浴场步道"),P("일광천 산책로","Ilgwangcheon Stream trail","日光川散歩道","日光川步道")], L("약 3시간","About 3 hours","約3時間","约3小时"), L("오전 또는 오후","Morning or afternoon","午前または午後","上午或下午"), ["quiet","walk","family","solo","morning","afternoon","easy","day-sea","uncrowded","nature"], L("일광 해변과 인접한 일광천 산책로를 편하게 이어 걸으며 한적하게 쉬기 좋아요.","The beach and adjacent Ilgwangcheon trail make an easy, peaceful walk for solo travelers or families.","海辺と隣接する日光川散歩道を気軽に歩き、静かに休めます。","海滩与邻近日光川步道轻松相连，适合独自或家庭安静休息。")),
    course("rec-imrang-rest", "imrang", L("임랑 조용한 휴식 코스","Peaceful Imrang Retreat","林浪静かな休息コース","林浪安静休闲路线"), [P("임랑해수욕장","Imrang Beach","林浪海水浴場","林浪海水浴场"),P("임랑해수욕장 산책로","Imrang Beach promenade","林浪海水浴場散歩道","林浪海水浴场步道"),P("임랑해수욕장 쉼터","Imrang Beach rest area","林浪海水浴場休憩所","林浪海水浴场休息区")], L("약 2시간 30분","About 2.5 hours","約2時間30分","约2.5小时"), L("낮","Daytime","昼","白天"), ["quiet","walk","nature","solo","family","afternoon","easy","day-sea","uncrowded"], L("이동을 최소화하고 임랑 해변의 산책로와 공용 쉼터에서 조용히 쉬는 코스예요.","Minimal travel and public beachfront rest areas make this a calm, uncrowded retreat.","移動を抑え、林浪の海辺の散歩道と公共休憩所で静かに過ごすコースです。","减少移动，在林浪海滨步道与公共休息区安静放松。")),
    course("rec-gijang-scenery", "songjeong", L("기장 바다 풍경 코스","Gijang Coastal Scenery","機張海景コース","机张海景路线"), [P("송정해수욕장","Songjeong Beach","松亭海水浴場","松亭海水浴场"),P("해동용궁사","Haedong Yonggungsa Temple","海東龍宮寺","海东龙宫寺"),P("오시리아 해안산책로","Osiria Coastal Trail","オシリア海岸散歩道","奥西里亚海岸步道")], L("약 6시간","About 6 hours","約6時間","约6小时"), L("오전부터 오후","Morning to afternoon","午前から午後","上午至下午"), ["photo","nature","family","morning","afternoon","many","day-sea","famous","walk"], L("송정에서 해동용궁사와 오시리아 해안으로 북상하는 동선으로 바다 풍경과 문화를 함께 만나요.","Travel north from Songjeong to Haedong Yonggungsa and Osiria for coast and culture in one day.","松亭から海東龍宮寺、オシリア海岸へ北上し、海景と文化を一緒に楽しめます。","从松亭向北前往海东龙宫寺和奥西里亚海岸，兼赏海景与文化。")),
    course("rec-busan-full-day", "haeundae", L("부산 바다 하루 완성 코스","Complete Busan Seaside Day","釜山海一日満喫コース","釜山海滨完整一日路线"), [P("해운대해수욕장","Haeundae Beach","海雲台海水浴場","海云台海水浴场"),P("동백섬","Dongbaekseom Island","冬柏島","冬柏岛"),P("광안리해수욕장","Gwangalli Beach","広安里海水浴場","广安里海水浴场"),P("광안대교 야경 조망","Gwangan Bridge night view","広安大橋の夜景","广安大桥夜景")], L("약 8시간","About 8 hours","約8時間","约8小时"), L("하루","Full day","一日","全天"), ["lively","photo","family","friends","full-day","many","day-sea","night","famous"], L("해운대의 낮 풍경부터 광안리 야경까지 대표 명소를 대중교통으로 잇는 첫 방문용 하루 코스예요.","A full first-visit itinerary links Haeundae by day to Gwangalli at night via public transit.","海雲台の昼景色から広安里の夜景まで、定番名所を公共交通で結ぶ一日コースです。","乘公共交通串联海云台白日风光与广安里夜景，适合初次到访的一日游。"))
  ];
  const weights = { mood: 3, companion: 2, activity: 3, time: 2, pace: 1, view: 3, crowd: 2 };
  function recommend(answers, limit = 3) {
    const values = Object.entries(answers).filter(([, value]) => value);
    const ranked = courses.map((item, index) => ({ item, index, score: values.reduce((sum, [key, value]) => sum + (item.tags.includes(value) ? (weights[key] || 1) : 0), 0) }))
      .sort((a, b) => b.score - a.score || a.index - b.index);
    const picked = [];
    for (const candidate of ranked) if (!picked.some((entry) => entry.item.beach === candidate.item.beach)) { picked.push(candidate); if (picked.length === limit) break; }
    for (const candidate of ranked) if (picked.length < limit && !picked.includes(candidate)) picked.push(candidate);
    return picked;
  }
  const api = { courses, recommend, localize: (value, language) => value?.[language] ?? value?.ko ?? value };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  root.BacochuRecommendations = api;
})(typeof window !== "undefined" ? window : globalThis);
