const assert = require("node:assert/strict");
const { courses, recommend, localize } = require("../recommendation-data.js");
assert.equal(courses.length, 14, "14 new built-in courses must remain available");
assert.deepEqual([...new Set(courses.map((course) => course.beach))].sort(), ["dadaepo","gwangalli","haeundae","ilgwang","imrang","songdo","songjeong"]);
for (const course of courses) for (const field of [course.name, course.duration, course.timeLabel, course.reason, ...course.places]) for (const language of ["ko","en","ja","zh-CN"]) assert.ok(localize(field, language));
const quiet = recommend({ mood:"quiet", companion:"solo", activity:"walk", time:"morning", pace:"easy", view:"sunrise", crowd:"uncrowded" });
const lively = recommend({ mood:"lively", companion:"family", activity:"sea", time:"afternoon", pace:"many", view:"day-sea", crowd:"famous" });
assert.equal(quiet.length, 3); assert.equal(lively.length, 3);
assert.equal(new Set(quiet.map(({item}) => item.beach)).size, 3);
assert.notDeepEqual(quiet.map(({item}) => item.id), lively.map(({item}) => item.id));
console.log("recommendation data: ok");
